### ISSUE TITLE
more trials

### ISSUE THREAD

**Issue by jojo12** [betweenbrain/Email-Additional-Fields#5] opened 2015-04-04 14:07 UTC
I added $data in components/com_contact/controllers/contact.php at the end of the email.

```
// Prepare email body
$prefix = JText::sprintf('COM_CONTACT_ENQUIRY_TEXT', JUri::base());
$body   = $prefix . "\n" . $name . ' <' . $email . '>' . "\r\n\r\n" . stripslashes($body) . $data;
```

the result is after the contact_message:
Array

I am not a developer, but it seems the entered data from form is not present in this file.

**Comment by betweenbrain** [comment] 2015-04-06 14:43
Hello,

If you change that to `$body    = $prefix . "\n" . $name . ' <' . $email . '>' . "\r\n\r\n" . stripslashes($body) . print_r($data, true);` you should see something like the following in the email you receive:

```
(
    [contact_name] => Matt Thomas
    [contact_email] => matt@betweenbrain.com
    [contact_subject] => Test
    [contact_message] => Hello
    [customfields] => Array
        (
            [company] => betweenbrain llc.
            [street] =>
            [city] =>
            [zip] =>
            [country] =>
        )

)
```

**Comment by jojo12** [comment] 2015-04-06 15:47
I got:

Dies ist eine Kontaktmail via http://www.kath-jugend.ch/ von:

Jojo Murer talitakum@bluewin.ch

Test mit HilfeArray

(

```
[contact_name] => Jojo Murer

[contact_email] => talitakum@bluewin.ch

[contact_subject] => Test mit Hilfe

[contact_message] => Test mit Hilfe

[customfields] => Array

    (

        [event] => Heimosterkerzen

        [eventdate] => Ostern

    )
```

)

I will take away the password and reactivate tester

sorry.

Jojo

Von: Matt Thomas [mailto:notifications@github.com] 
Gesendet: Montag, 6. April 2015 16:43
An: betweenbrain/Email-Additional-Fields
Cc: jojo12
Betreff: Re: [Email-Additional-Fields] more trials (#5)

Hello,

If you change that to $body = $prefix . "\n" . $name . ' <' . $email . '>' . "\r\n\r\n" . stripslashes($body) . print_r($data, true); you should see something like the following in the email you receive:

(
    [contact_name] => Matt Thomas
    [contact_email] => matt@betweenbrain.com
    [contact_subject] => Test
    [contact_message] => Hello
    [customfields] => Array
        (
            [company] => betweenbrain llc.
            [street] =>
            [city] =>
            [zip] =>
            [country] =>
        )

)

**Comment by betweenbrain** [comment] 2015-04-06 16:03
That's great that you are seeing the custom fields

```
 [customfields] => Array
        (
            [event] => Heimosterkerzen
            [eventdate] => Ostern
        )
```

I'm still confused about what else may be preventing this from working for you.

**Comment by jojo12** [comment] 2015-04-06 16:10
I changed now your original custom fields

and get

Dies ist eine Kontaktmail via http://www.kath-jugend.ch/ von:

Jojo jojo.murer@bluewin.ch

Test originalArray

(

```
[contact_name] => Jojo

[contact_email] => jojo.murer@bluewin.ch

[contact_subject] => Test original

[contact_message] => Test original

[customfields] => Array

    (

        [company] => Firma

        [street] => Erlenweg 5

        [city] => Oberentfelden

        [zip] => 5036

        [country] => Schweiz

    )
```

)

Von: Matt Thomas [mailto:notifications@github.com] 
Gesendet: Montag, 6. April 2015 18:03
An: betweenbrain/Email-Additional-Fields
Cc: jojo12
Betreff: Re: [Email-Additional-Fields] more trials (#5)

That's great that you are seeing the custom fields

 [customfields] => Array
        (
            [event] => Heimosterkerzen
            [eventdate] => Ostern
        )

I'm still confused about what else may be preventing this from working for you.

**Comment by jojo12** [comment] 2015-04-06 16:11
in dropdown menu of home

there is kontakt and the contact to you testperson allgemein has your email.

Jojo

Von: Matt Thomas [mailto:notifications@github.com] 
Gesendet: Montag, 6. April 2015 18:03
An: betweenbrain/Email-Additional-Fields
Cc: jojo12
Betreff: Re: [Email-Additional-Fields] more trials (#5)

That's great that you are seeing the custom fields

 [customfields] => Array
        (
            [event] => Heimosterkerzen
            [eventdate] => Ostern
        )

I'm still confused about what else may be preventing this from working for you.

**Comment by betweenbrain** [comment] 2015-04-06 18:24
Hello,

Unfortunately, I cannot tell from the backend what may be wrong. Maybe I can with a back up of the site.

If you change components/com_contact/controllers/contact.php:131 to

```
        JFactory::getApplication()->enqueueMessage('<pre>Before plugin: ' . print_r($data['contact_message'], true) . '</pre>');

        // Passed Validation: Process the contact plugins to integrate with other applications
        $dispatcher->trigger('onSubmitContact', array(&$contact, &$data));

        JFactory::getApplication()->enqueueMessage('<pre>After plugin: ' . print_r($data['contact_message'], true) . '</pre>');
```

You should see something like this image. The area in red are the fields added to the email by this plugin. Please keep in mind that the custom fields plugin seems to be working fine, it's that the Email Additional Fields plugin that is having an issue or conflict.
![screenshot - 04062015 - 02 22 00 pm](https://cloud.githubusercontent.com/assets/634119/7009492/9dc60782-dc68-11e4-9c9f-54da42a289cc.jpg)

**Comment by jojo12** [comment] 2015-04-06 19:32
I have received this notice (see image)

Jojo

Von: Matt Thomas [mailto:notifications@github.com] 
Gesendet: Montag, 6. April 2015 20:25
An: betweenbrain/Email-Additional-Fields
Cc: jojo12
Betreff: Re: [Email-Additional-Fields] more trials (#5)

Hello,

Unfortunately, I cannot tell from the backend what may be wrong. Maybe I can with a back up of the site.

If you change components/com_contact/controllers/contact.php:131 to

```
    JFactory::getApplication()->enqueueMessage('<pre>Before plugin: ' . print_r($data['contact_message'], true) . '</pre>');

    // Passed Validation: Process the contact plugins to integrate with other applications
    $dispatcher->trigger('onSubmitContact', array(&$contact, &$data));

    JFactory::getApplication()->enqueueMessage('<pre>After plugin: ' . print_r($data['contact_message'], true) . '</pre>');
```

You should see something like this image. The area in red are the fields added to the email by this plugin. Please keep in mind that the custom fields plugin seems to be working fine, it's that the Email Additional Fields plugin that is having an issue or conflict.
 https://cloud.githubusercontent.com/assets/634119/7009492/9dc60782-dc68-11e4-9c9f-54da42a289cc.jpg screenshot - 04062015 - 02 22 00 pm

**Comment by betweenbrain** [comment] 2015-04-06 23:12
Hello,

Unfortunately, I do not see any image attached.

**Comment by jojo12** [comment] 2015-04-07 06:17
![testnachricht](https://cloud.githubusercontent.com/assets/2960236/7017914/9531f0ea-dcfe-11e4-8286-470c87900516.png)
sorry

**Comment by betweenbrain** [comment] 2015-04-07 11:17
No problem, thanks for all of your help in investigating this issue.

It seems that the Email Additional Fields plugin is either not working, or another extension is overriding it. As I have been unable to reproduce the issue with a clean install of Joomla, without any other extensions, I am suspicious that anot her third-party extension is hijacking the `$data` object and undoing what my plugin is.

Would it be possible to get a copy of yoir site so that I can inspect the code? I would install it only locally to troubleshoot this issue then delete it.

If not, you may try disabling all installed extensions and then test the form. If the added fields are in the email, then enable the extensions one by one to see which one is breaking it.

**Comment by jojo12** [comment] 2015-04-07 13:00
Sorry, I can't send you a copy (for safety reasons, because it's not only mine)

But I made a clean install of joomla 3.4.1 with no others extensions (only your two plugins are installed and enabled). The form is there, but in emails there is all the same! 
I can't understand you can't reproduce this problem.
![sysinfo](https://cloud.githubusercontent.com/assets/2960236/7023601/c85ce708-dd36-11e4-95c4-555331156687.png)

**Comment by betweenbrain** [comment] 2015-04-07 14:30
> Sorry, I can't send you a copy (for safety reasons, because it's not only mine)

No problem, I completely understand.

> But I made a clean install of joomla 3.4.1 with no others extensions (only your two plugins are installed and enabled). The form is there, but in emails there is all the same! I can't understand you can't reproduce this problem.

That's strange, and I can't understand it either.

But... I have just launched a new web server and have been able to reproduce it there. That's a good step, but odd that it works some places and not others.

I'll keep you posted.

**Comment by jojo12** [comment] 2015-04-07 14:33
Yeah, that's just one step coming together :)

**Comment by betweenbrain** [comment] 2015-04-07 15:16
When you have a chance, please try version 1.0.2 at https://github.com/betweenbrain/Email-Additional-Fields/releases/tag/1.0.2

**Comment by jojo12** [comment] 2015-04-07 15:40
I tried with the clean Joomla 3.4.1 and only your plugins installed and enabled.
and I got the following email:
![mail1 0 2](https://cloud.githubusercontent.com/assets/2960236/7027107/1203e70a-dd4e-11e4-967a-d1e1c5cf4f6a.png)

And controller/contact.php is not hacked!
looks just very good!

**Comment by jojo12** [comment] 2015-04-07 15:42
and here's the copy of the mail:
![mailcopy](https://cloud.githubusercontent.com/assets/2960236/7027118/1daa07ba-dd4e-11e4-97ab-25415a47f880.png)

**Comment by betweenbrain** [comment] 2015-04-07 15:44
That is fantastic! Thank you for your help in resolving this.

Please let me know if you have any other questions, or feature requests, by opening a new issue.

Best,
Matt

**Closed as completed by betweenbrain** 2015-04-07 15:44 UTC

**Comment by betweenbrain** [comment] 2015-04-07 19:09
PS: This has been submitted to the JED - http://extensions.joomla.org/extensions/extension/contacts-and-feedback/forms/emai-additional-fields. Reviews, and feature requests here as new issues, are always warmly welcomed.
